In [10]:
import numpy as np
import pandas as pd

In [11]:
#Load dataset
dfDataChampionship            =  pd.read_csv("campeonato-brasileiro-full.csv", delimiter=",")

#To String
dfDataChampionship            =  dfDataChampionship.applymap(str);  

#Create new column Placar
dfDataChampionship["Placar"]  =  dfDataChampionship["Clube 1 Gols"].map(str) + "x" + dfDataChampionship["Clube 2 Gols"]

#Show data
dfDataChampionship.head()

,Horário,Dia,Data,Clube 1,Clube 2,Vencedor,Rodada,Arena,Clube 1 Gols,Clube 2 Gols,Clube 1 Estado,Clube 2 Estado,Estado Clube Vencedor,Placar
0,16h00,Sábado,2000-07-29,Fluminense,Bahia,Fluminense,1ª Rodada,Maracanã,2,0,RJ,BA,RJ,2x0
1,16h00,Sábado,2000-07-29,Vasco,Sport,Sport,1ª Rodada,São Januário,0,2,RJ,PE,PE,0x2
2,16h00,Sábado,2000-07-29,Vitória,Palmeiras,Vitória,1ª Rodada,Barradão,4,1,ES,SP,ES,4x1
3,17h00,Domingo,2000-07-30,Botafogo-RJ,Atlético-MG,-,1ª Rodada,Caio Martins,0,0,RJ,MG,Empate,0x0
4,18h30,Domingo,2000-07-30,Juventude,Flamengo,-,1ª Rodada,Alfredo Jaconi,1,1,RS,RJ,Empate,1x1

In [12]:
d = {'Clubes': [], 'PG': [], 'j': [], 'V': [], 'E': [], 'D': [], 'GP': [], 'GC': [], 'SG': []}
dfClassChampionship = pd.DataFrame(data=d);

In [13]:
filter1  =  dfDataChampionship['Data']>='2015-01-01'
filter2  =  dfDataChampionship['Data']<='2015-12-31'
brasilianLeague2015 = dfDataChampionship[filter1 & filter2]
brasilianLeague2015.head()

,Horário,Dia,Data,Clube 1,Clube 2,Vencedor,Rodada,Arena,Clube 1 Gols,Clube 2 Gols,Clube 1 Estado,Clube 2 Estado,Estado Clube Vencedor,Placar
6039,18h30,Sábado,2015-05-09,Palmeiras,Atlético-MG,-,1ª Rodada,Allianz Parque,2,2,SP,MG,Empate,2x2
6040,18h30,Sábado,2015-05-09,Chapecoense,Coritiba,Chapecoense,1ª Rodada,Arena Condá,2,1,SC,PR,SC,2x1
6041,21h00,Sábado,2015-05-09,Fluminense,Joinville,Fluminense,1ª Rodada,Maracanã,1,0,RJ,SC,RJ,1x0
6042,18h30,Domingo,2015-05-10,Vasco,Goiás,-,1ª Rodada,São Januário,0,0,RJ,GO,Empate,0x0
6043,11h00,Domingo,2015-05-10,Grêmio,Ponte Preta,-,1ª Rodada,Arena do Grêmio,3,3,RS,SP,Empate,3x3

In [14]:
#Cancatenando as colunas Clube 1 e Clube 2
clubs  =  pd.concat([brasilianLeague2015['Clube 1'].str.lower(), brasilianLeague2015['Clube 2'].str.lower()], axis=1, keys=['Clubes'])

In [15]:
#Obtem todos os clubes 
cb  =  pd.Series(clubs['Clubes'].unique(), name="Clubes")
cb  =  cb.to_frame()
cb

           Clubes
0       palmeiras
1     chapecoense
2      fluminense
3           vasco
4          grêmio
5            avaí
6    athlético-pr
7        cruzeiro
8       são paulo
9           sport
10    corinthians
11       coritiba
12          goiás
13      joinville
14       flamengo
15    figueirense
16    atlético-mg
17  internacional
18    ponte preta
19         santos

In [16]:
def getNumberWinner(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter = df["Vencedor"].str.lower() == clube
    return (data[filter]['Vencedor'].count()).astype(np.int64)

def getNumberDepartures(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = df["Clube 1"].str.lower() == clube
    filter2 = df["Clube 2"].str.lower() == clube
    return (data[filter1]['Clube 1'].count() + data[filter2]['Clube 2'].count()).astype(np.int64)

def getPoints(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = df["Clube 1"].str.lower() == clube
    filter2 = df["Clube 2"].str.lower() == clube
    filter3 = df["Vencedor"].str.lower() == clube
    filter4 = (df["Clube 1"].str.lower() == clube) | (df["Clube 2"].str.lower() == clube)
    filter5 = df["Vencedor"].str.lower() == '-'
    brasilianLeagle2015
    v1 = data[(filter1) & (filter3)]
    v1 = v1['Vencedor'].count()
    v2 = data[(filter2) & (filter3)]
    v2 = v2['Vencedor'].count() 
    v3 = data[(filter4) & (filter5)]
    v3 = v3['Vencedor'].count()
    return ((v2*3)+(v1*3)+v3).astype(np.int64)

def getDraw(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = (df["Clube 1"].str.lower() == clube) | (df["Clube 2"].str.lower() == clube)
    filter2 = df["Vencedor"].str.lower() == '-'
    df = data[(filter1) & (filter2)]
    empates = df['Vencedor'].count()
    return empates.astype(np.int64)

def getDefeats(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = (df["Clube 1"].str.lower() == clube) | (df["Clube 2"].str.lower() == clube)
    filter2 = (df["Vencedor"].str.lower() != clube) & (df["Vencedor"].str.lower() != '-')
    df = data[(filter1) & (filter2)]
    derrotas = df['Vencedor'].count()
    return derrotas.astype(np.int64)

def getGP(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1  =  df["Clube 1"].str.lower() == clube
    filter2  =  df["Clube 2"].str.lower() == clube
    df1      =  data[(filter1)]
    df2      =  data[(filter2)]
    placar1  =  df1['Placar'].str.split('x')
    placar2  =  df2['Placar'].str.split('x')
    
    gp       =  0
    gc       =  0
    for g1, g2 in placar1:
        gp = (gp + pd.to_numeric( g1 ))
        gc = (gc + pd.to_numeric( g2 ))
            
    for g1, g2 in placar2:brasilianLeagle2015
        gp = (gp + pd.to_numeric( g2 )) 
        gc = (gc + pd.to_numeric( g1 ))
    return gp, gc

IndentationError: unexpected indent (<ipython-input-16-8edbd7a6baaf>, line 60)

In [17]:

dfTable = cb[["Clubes"]].copy()
for column in ["PG", "J", "V", "E", "D", "GP", "GC", "SG"]:
    dfTable[column] = 0

def ensureUtf(s, encoding='utf8'):
  if type(s) == bytes:
    return s.decode(encoding, 'ignore')
  else:
    return s

for index, row in dfTable.iterrows():
    c1  =  row['Clubes']
    c1  =  ensureUtf( c1 )
    c1  =  c1.strip()
    
    pg       =  getPoints(brasilianLeague2015, c1 )
    j        =  getNumberDepartures(brasilianLeague2015, c1 )
    v        =  getNumberWinner(brasilianLeague2015, c1 )
    e        =  getDraw(brasilianLeague2015, c1 )
    d        =  getDefeats(brasilianLeague2015, c1 )
    gp, gc   =  getGP(brasilianLeague2015, c1 )
    
    
    dfTable.at[index, 'PG'] = pg
    dfTable.at[index, 'J']  = j
    dfTable.at[index, 'V']  = v
    dfTable.at[index, 'E']  = e
    dfTable.at[index, 'D']  = d
    dfTable.at[index, 'GP'] = gp
    dfTable.at[index, 'GC'] = gc
    dfTable.at[index, 'SG'] = gp - gc

dfTable['Clubes'] = dfTable['Clubes'].str.capitalize() 
dfTable  =  dfTable.sort_values(by=['PG', 'J', 'V', 'E', 'D', 'GP'], ascending=False)
dfTable  =  dfTable.reset_index(drop=True)
dfTable

           Clubes  PG   J   V   E   D  GP  GC  SG
0     Corinthians  81  38  24   9   5  71  31  40
1     Atlético-mg  69  38  21   6  11  65  47  18
2          Grêmio  68  38  20   8  10  52  32  20
3       São paulo  62  38  18   8  12  53  47   6
4   Internacional  60  38  17   9  12  39  38   1
5           Sport  59  38  15  14   9  53  38  15
6          Santos  58  38  16  10  12  59  41  18
7        Cruzeiro  55  38  15  10  13  44  35   9
8       Palmeiras  53  38  15   8  15  60  51   9
9    Athlético-pr  51  38  14   9  15  43  48  -5
10    Ponte preta  51  38  13  12  13  41  40   1
11       Flamengo  49  38  15   4  19  45  53  -8
12     Fluminense  47  38  14   5  19  40  49  -9
13    Chapecoense  47  38  12  11  15  34  44 -10
14       Coritiba  44  38  11  11  16  31  42 -11
15    Figueirense  43  38  11  10  17  36  50 -14
16           Avaí  42  38  11   9  18  38  60 -22
17          Vasco  41  38  10  11  17  28  54 -26
18          Goiás  38  38  10   8  20  39  49 -10
19      Joinville  31  38   7  10  21  26  48 -22