In [1]:
import numpy as np
import pandas as pd

In [9]:
#Load dataset
dfDataChampionship            =  pd.read_csv("campeonato-brasileiro-full.csv", delimiter=",")

#To String
dfDataChampionship            =  dfDataChampionship.applymap(str);  

#Create new column Placar
dfDataChampionship["Placar"]  =  dfDataChampionship["Clube 1 Gols"].map(str) + "x" + dfDataChampionship["Clube 2 Gols"]

#Show data
dfDataChampionship.head()

,Horário,Dia,Data,Clube 1,Clube 2,Vencedor,Rodada,Arena,Clube 1 Gols,Clube 2 Gols,Clube 1 Estado,Clube 2 Estado,Estado Clube Vencedor,Placar
0,16h00,Sábado,2000-07-29,Fluminense,Bahia,Fluminense,1ª Rodada,Maracanã,2,0,RJ,BA,RJ,2x0
1,16h00,Sábado,2000-07-29,Vasco,Sport,Sport,1ª Rodada,São Januário,0,2,RJ,PE,PE,0x2
2,16h00,Sábado,2000-07-29,Vitória,Palmeiras,Vitória,1ª Rodada,Barradão,4,1,ES,SP,ES,4x1
3,17h00,Domingo,2000-07-30,Botafogo-RJ,Atlético-MG,-,1ª Rodada,Caio Martins,0,0,RJ,MG,Empate,0x0
4,18h30,Domingo,2000-07-30,Juventude,Flamengo,-,1ª Rodada,Alfredo Jaconi,1,1,RS,RJ,Empate,1x1

In [10]:
d = {'Clubes': [], 'PG': [], 'j': [], 'V': [], 'E': [], 'D': [], 'GP': [], 'GC': [], 'SG': []}
dfClassChampionship = pd.DataFrame(data=d);

In [11]:
filter1  =  dfDataChampionship['Data']>='2016-01-01'
filter2  =  dfDataChampionship['Data']<='2016-12-31'
brasilianLeague2016 = dfDataChampionship[filter1 & filter2]
brasilianLeague2016.head()

,Horário,Dia,Data,Clube 1,Clube 2,Vencedor,Rodada,Arena,Clube 1 Gols,Clube 2 Gols,Clube 1 Estado,Clube 2 Estado,Estado Clube Vencedor,Placar
6419,18:30,Sábado,2016-05-14,Atlético-MG,Santos,Atlético-MG,1ª Rodada,Independência,1,0,MG,SP,MG,1x0
6420,21:00,Sábado,2016-05-14,Coritiba,Cruzeiro,Coritiba,1ª Rodada,Couto Pereira,1,0,PR,MG,PR,1x0
6421,16:00,Sábado,2016-05-14,Flamengo,Sport,Flamengo,1ª Rodada,Raulino de Oliveira,1,0,RJ,PE,RJ,1x0
6422,16:00,Sábado,2016-05-14,Palmeiras,Athlético-PR,Palmeiras,1ª Rodada,Palestra Itália,4,0,SP,PR,SP,4x0
6423,18:30,Domingo,2016-05-15,Internacional,Chapecoense,-,1ª Rodada,Beira Rio,0,0,RS,SC,Empate,0x0

In [12]:
#Cancatenando as colunas Clube 1 e Clube 2
clubs  =  pd.concat([brasilianLeague2016['Clube 1'].str.lower(), brasilianLeague2016['Clube 2'].str.lower()], axis=1, keys=['Clubes'])

In [13]:
#Obtem todos os clubes 
cb  =  pd.Series(clubs['Clubes'].unique(), name="Clubes")
cb  =  cb.to_frame()
cb

           Clubes
0     atlético-mg
1        coritiba
2        flamengo
3       palmeiras
4   internacional
5     corinthians
6     figueirense
7      américa-mg
8      santa cruz
9     botafogo-rj
10       cruzeiro
11     fluminense
12    ponte preta
13   athlético-pr
14          sport
15    chapecoense
16         grêmio
17      são paulo
18         santos
19        vitória

In [14]:
brasilianLeagbrasilianLeagle2016le2017def getNumberWinner(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter = df["Vencedor"].str.lower() == clube
    return (data[filter]['Vencedor'].count()).astype(np.int64)

def getNumberDepartures(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = df["Clube 1"].str.lower() == clube
    filter2 = df["Clube 2"].str.lower() == clube
    return (data[filter1]['Clube 1'].count() + data[filter2]['Clube 2'].count()).astype(np.int64)

def getPoints(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = df["Clube 1"].str.lower() == clube
    filter2 = df["Clube 2"].str.lower() == clube
    filter3 = df["Vencedor"].str.lower() == clube
    filter4 = (df["Clube 1"].str.lower() == clube) | (df["Clube 2"].str.lower() == clube)
    filter5 = df["Vencedor"].str.lower() == '-'
    
    v1 = data[(filter1) & (filter3)]
    v1 = v1['Vencedor'].count()
    v2 = data[(filter2) & (filter3)]
    v2 = v2['Vencedor'].count() 
    v3 = data[(filter4) & (filter5)]
    v3 = v3['Vencedor'].count()
    return ((v2*3)+(v1*3)+v3).astype(np.int64)

def getDraw(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = (df["Clube 1"].str.lower() == clube) | (df["Clube 2"].str.lower() == clube)
    filter2 = df["Vencedor"].str.lower() == '-'
    df = data[(filter1) & (filter2)]
    empates = df['Vencedor'].count()
    return empates.astype(np.int64)

def getDefeats(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = (df["Clube 1"].str.lower() == clube) | (df["Clube 2"].str.lower() == clube)
    filter2 = (df["Vencedor"].str.lower() != clube) & (df["Vencedor"].str.lower() != '-')
    df = data[(filter1) & (filter2)]
    derrotas = df['Vencedor'].count()
    return derrotas.astype(np.int64)

def getGP(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1  =  df["Clube 1"].str.lower() == clube
    filter2  =  df["Clube 2"].str.lower() == clube
    df1      =  data[(filter1)]
    df2      =  data[(filter2)]
    placar1  =  df1['Placar'].str.split('x')
    placar2  =  df2['Placar'].str.split('x')
    
    gp       =  0
    gc       =  0
    for g1, g2 in placar1:
        gp = (gp + pd.to_numeric( g1 ))
        gc = (gc + pd.to_numeric( g2 ))
            
    for g1, g2 in placar2:
        gp = (gp + pd.to_numeric( g2 )) 
        gc = (gc + pd.to_numeric( g1 ))
    return gp, gc

SyntaxError: invalid syntax (<ipython-input-14-6d8ab9838ee5>, line 1)

In [15]:

dfTable = cb[["Clubes"]].copy()
for column in ["PG", "J", "V", "E", "D", "GP", "GC", "SG"]:
    dfTable[column] = 0

def ensureUtf(s, encoding='utf8'):
  if type(s) == bytes:
    return s.decode(encoding, 'ignore')
  else:
    return s

for index, row in dfTable.iterrows():
    c1  =  row['Clubes']
    c1  =  ensureUtf( c1 )
    c1  =  c1.strip()
    
    pg       =  getPoints(brasilianLeague2016, c1 )
    j        =  getNumberDepartures(brasilianLeague2016, c1 )
    v        =  getNumberWinner(brasilianLeague2016, c1 )
    e        =  getDraw(brasilianLeague2016, c1 )
    d        =  getDefeats(brasilianLeague2016, c1 )
    gp, gc   =  getGP(brasilianLeague2016, c1 )
    
    if c1 == "atlético-mg" or c1 == "chapecoense" :
        pg  =  pg-1
        e   =  e-1
        d   =  d+1    
    
    dfTable.at[index, 'PG'] = pg
    dfTable.at[index, 'J']  = j
    dfTable.at[index, 'V']  = v
    dfTable.at[index, 'E']  = e
    dfTable.at[index, 'D']  = d
    dfTable.at[index, 'GP'] = gp
    dfTable.at[index, 'GC'] = gc
    dfTable.at[index, 'SG'] = gp - gc

dfTable['Clubes'] = dfTable['Clubes'].str.capitalize() 
dfTable  =  dfTable.sort_values(by=['PG', 'J', 'V', 'E', 'D', 'GP'], ascending=False)
dfTable  =  dfTable.reset_index(drop=True)
dfTable

           Clubes  PG   J   V   E   D  GP  GC  SG
0       Palmeiras  80  38  24   8   6  62  32  30
1          Santos  71  38  22   5  11  59  35  24
2        Flamengo  71  38  20  11   7  52  35  17
3     Atlético-mg  62  38  17  11  10  61  50  11
4     Botafogo-rj  59  38  17   8  13  43  39   4
5    Athlético-pr  57  38  17   6  15  38  32   6
6     Corinthians  55  38  15  10  13  48  42   6
7     Ponte preta  53  38  15   8  15  48  52  -4
8          Grêmio  53  38  14  11  13  41  44  -3
9       São paulo  52  38  14  10  14  44  36   8
10    Chapecoense  52  38  13  13  12  49  53  -4
11       Cruzeiro  51  38  14   9  15  48  49  -1
12     Fluminense  50  38  13  11  14  45  45   0
13          Sport  47  38  13   8  17  49  55  -6
14       Coritiba  46  38  11  13  14  41  42  -1
15        Vitória  45  38  12   9  17  51  53  -2
16  Internacional  43  38  11  10  17  35  41  -6
17    Figueirense  37  38   8  13  17  30  50 -20
18     Santa cruz  31  38   8   7  23  45  69 -24
19     América-mg  28  38   7   7  24  23  58 -35

### Problema com os dados do clube Atlético-MG
##### Ocorreu um problema com a tabela, ao confrontar os dados com a tabela da CBF, os dados de GC e SG, na tabela da CBF: GC=53 e SG=8.

### Problema com os dados do clube Chapecoense
##### Ocorreu um problema com a tabela, ao confrontar os dados com a tabela da CBF, os dados de GC e SG, na tabela da CBF: GC=56 e SG=-7.

###### A tragédia com os dirigentes e jogadores da Chapecoense fez com que o Atlético-MG não disputasse o jogo da 38ª rodada do Brasileirão, resultando um W.O. duplo.

### Dados oficiais da CBF
https://www.cbf.com.br/futebol-brasileiro/competicoes/campeonato-brasileiro-serie-a/2016